### PR TITLE
feat: add BSW token

### PR DESCRIPTION
**Pull request by ivicmad**

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Hey! Thanks for submitting. Could you please add a coinGeckoId to this config?

**Review by ecdsafu — APPROVED** [review]
lgtm

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Sorry guys could you please add the BSW token in svg format with a solid circle background so the icon reference URL works?

**Comment by blurrytweaks** [comment]
Add this one if it works for you, thanks!

bsw

**Review by blurrytweaks — APPROVED** [review]
lgtm!

**Review by ecdsafu — APPROVED** [review]
Lgtm

**Pull request closed without merging**
