### PR TITLE
feat: add UNV token

### PR DESCRIPTION
**Pull request by ubinatus**
Hello Axelar Team! Creating this PR to add our UNV token to Squid.

We are Unvest (https://unvest.io), a permissionless platform that offers a range of services for managing tokens, including custom vesting, liquidity locks, token creation, staking, farming, and airdropping.

We really enjoyed the process of creating our interchain tokens with you guys. Have a great one!

### CODE REVIEW

**Review by blurrytweaks — CHANGES_REQUESTED** [review]
Hi what's up! could you please replace that .svg for this one?
unv
the other thing if you can, is to add it's coingecko ID as it shows:
```tsx
      "tokenId": "0x0d63c47f94b9ea669bb70e03790632d7d358b4ce3ffa275d429f0c3d8a283b8f",
      "coinGeckoId": "unvest",
      "deployer": "0x758E6608122B5da9c40B81b928e8d0e518630134",
```
Thank you so much!

**Comment by ubinatus** [comment]
Done! Thanks for the info!

**Review by blurrytweaks — APPROVED** [review]
Hey, thank you so much! lgtm

**Review by ecdsafu — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
