### PR TITLE
feat: add CHRP token

### PR DESCRIPTION
**Pull request by 2infinity-gh**
latest request

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Thanks for submitting! Could you please add a coingeckoId and svg image?

**Comment by 2infinity-gh** [comment]
> Thanks for submitting! Could you please add a coinGeckoId and svg image?

done

**Review by Olanetsoft — APPROVED** [review]

**Review by canhtrinh — APPROVED** [review]

**Review by ecdsafu — APPROVED** [review]
lgtm

**Comment by canhtrinh** [comment]
closed in #88

**Pull request closed without merging**
