### PR TITLE
feat: add DACKIE token

### PR DESCRIPTION
**Pull request by andreapn**
add DACKIE token to Squid

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Thanks! Please add coingecko ID dackieswap and the svg icon

**Comment by Olanetsoft** [comment]
> https://www.coingecko.com/en/coins/dackieswap

Can you please add this to the PR and the SVG ?

**Comment by Olanetsoft** [comment]
> @Olanetsoft sure
> 
> dackie quack

@andreapn I mean you should add it as a commit to the PR itself. See an example [here](https://github.com/axelarnetwork/axelar-configs/pull/56)

**Review by ecdsafu — APPROVED** [review]
let's merge this and upload the images ourselves in another PR

**Pull request closed without merging**
