### PR TITLE
Add XAV token

### PR DESCRIPTION
**Pull request by schystz**
We want to list our XAV interchain token on Squid
https://interchain.axelar.dev/avalanche/0x913C61ec3573E5E4ee6488552535Fb1be84FF2AC

This PR is generated from `bun wizard` cmd

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Please set image to fit inside a circle
xav

**Comment by schystz** [comment]
Hi @ecdsafu, sorry I missed your message and was just able to update the image now. I've re-synced the branch as well to `main` and hope everything is good now, otherwise please let me know.

**Comment by schystz** [comment]
Hi @ecdsafu, pls let me know what else you need so we can merge this PR 🙏

**Review by ecdsafu — APPROVED** [review]
lgtm thanks!

**Review by canhtrinh — APPROVED** [review]

**Pull request merged**
