### PR TITLE
feat: add btsg logo

### PR DESCRIPTION
**Pull request by kalidax**

### CODE REVIEW

**Review by blurrytweaks — CHANGES_REQUESTED** [review]
Hi kalidax, could you please replace it for this svg?

btsg

**Comment by ecdsafu** [comment]
@Olanetsoft Not sure if blurrytweaks or I can edit this in place outside of our own forks. Would you be able to replace the logo so we can merge?

**Comment by canhtrinh** [comment]
@blurrytweaks - updated. looks good?

**Review by blurrytweaks — APPROVED** [review]
looks good cahtrinh, thanks kalidax!

**Pull request merged**
