### PR TITLE
add pstake token

### PR DESCRIPTION
**Pull request by ChipKlutzy**
Please review the following token assets:

## 📑 Description

-   Token Name: pSTAKE Finance
-   Project Website: https://pstake.finance/
-   Explorer URI: https://etherscan.io/token/0xfb5c6815ca3ac72ce9f5006869ae67f18bf77006

### CODE REVIEW

**Review by ecdsafu — APPROVED** [review]
lgtm

**Review by blurrytweaks — APPROVED** [review]
lgtm, thank you!

**Comment by canhtrinh** [comment]
@ChipKlutzy we noticed in your proposed config that you deployed lock-unlock token managers on all the remote chains. this is an invalid instantiation, and we don't think it will work (did you somehow get it to work and were successfully able to transfer tokens across chains?) cc @blockchainguyy

**Comment by canhtrinh** [comment]
Closing PR due to inactivity following this comment: https://github.com/axelarnetwork/axelar-configs/pull/106#issuecomment-2261343673

**Pull request closed without merging**
