### PR TITLE
feat: add OMKG token

### PR DESCRIPTION
**Pull request by alexandrecarvalheira**

### CODE REVIEW

**Comment by blurrytweaks** [comment]
Hi Alex, could you add it's coingecko ID under tokenID and the .svg please : )

**Comment by alexandrecarvalheira** [comment]
added the svg and coinGecko ID but also noticed that some of the data from the ITS was wrong and we manually fixed it.

**Review by blurrytweaks — CHANGES_REQUESTED** [review]
Hey! sweet, nice catch, could you please replace the svg for this one?
omkg

**Review by blurrytweaks — APPROVED** [review]
Thank you! lgtm.

**Review by canhtrinh — APPROVED** [review]

**Pull request merged**
