### PR TITLE
add gnus token

### PR DESCRIPTION
**Pull request by ruymaster**
- add interchain info for gnus token
- add gnus icon

### CODE REVIEW

**Review by blurrytweaks — CHANGES_REQUESTED** [review]
oh man! this way is so cool!

gnus

**Comment by ruymaster** [comment]
I updated token icon as you want.

**Comment by blurrytweaks** [comment]
> I updated token icon as you want.

**Comment by blurrytweaks** [comment]
Hey thanks a lot! just closed and reopened accidentally

**Pull request closed without merging**
