### PR TITLE
Add BCT on Base

### PR DESCRIPTION
**Pull request by cujowolf**
Add interchain Base deployment of BCT

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Hey @cujowolf thanks for submitting this. Could you add a coinGeckoId for this if it exists please?

**Review by ecdsafu — APPROVED** [review]
@canhtrinh I say we merge this and then fix the coingeckoID `base-carbon-tonne` and token svg (needs to be circle cropped) in a separate PR. I can make the fix PR

**Comment by cujowolf** [comment]
> @canhtrinh I say we merge this and then fix the coingeckoID `base-carbon-tonne` and token svg (needs to be circle cropped) in a separate PR. I can make the fix PR

Hey there. Should have the coingeckoId added in and rebased from main.

**Comment by ecdsafu** [comment]
> > @canhtrinh I say we merge this and then fix the coingeckoID `base-carbon-tonne` and token svg (needs to be circle cropped) in a separate PR. I can make the fix PR
> 
> Hey there. Should have the coingeckoId added in and rebased from main.

Looks good, thanks!

**Review by canhtrinh — APPROVED** [review]

**Review by npty — APPROVED** [review]

**Pull request merged**
