### PR TITLE
Feat/add alva token

### PR DESCRIPTION
**Pull request by ObjectPlayer**
Hello Axelar Team! Creating this PR to add our ALVA token to Squid.

I am from Alvara protocol https://alvara.xyz. The Alvara Protocol is a transformative platform in the DeFi space designed to democratize the world of asset management. Built on the newly developed ERC-7621 token standard, Alvara provides an innovative tokenized basket factory that paves the way for anyone to become a basket manager. 

I have already completed ITS process to deploy token managers for ALVA tokens for both chain Etheruem & Avalanche. Really enjoyed the process and done some token transfer from scripts. Now we want to add our token on Squid, so anyone can easily swap their tokens. 

I have already added all the needed information, kindly review it and let me know if there is anything missing from side. So I can add it. 

Thanks

### CODE REVIEW

**Review by ecdsafu — COMMENTED** [review]
Thanks for submitting! 

@ObjectPlayer could you please add a coinGeckoId if there is one for the token?

**Comment by ObjectPlayer** [comment]
Hey @ecdsafu, 

I have added coingecku-id in this PR, but can you confirm if `tokenType` is okay ? Actually it is showing `canonical` which is added by the wizard by default, let me know if we need to update. 

Thanks

**Comment by ecdsafu** [comment]
> Hey @ecdsafu,
> 
> I have added coingecku-id in this PR, but can you confirm if `tokenType` is okay ? Actually it is showing `canonical` which is added by the wizard by default, let me know if we need to update.
> 
> Thanks

Awesome, thanks. I'll approve, and let the Axelar team comment whether canonical is the right type

**Review by ecdsafu — APPROVED** [review]
lgtm

**Comment by canhtrinh** [comment]
looks fine. can you delete the package-lock file tho?

**Review by canhtrinh — APPROVED** [review]

**Pull request merged**
