### PR TITLE
Added GRAIN token

### PR DESCRIPTION
**Pull request by Deantoshi**

### CODE REVIEW

**Comment by canhtrinh** [comment]
can you rebase the latest in main?
@ecdsafu can you review svg?

**Comment by Deantoshi** [comment]
Synced to main. Let me know if there's anything else I need to do. Thank you!

**Review by ecdsafu — APPROVED** [review]
lgtm

**Comment by Deantoshi** [comment]
Good deal! Let me know if I need to provide/change anything to get this pushed through

**Pull request merged**
