### PR TITLE
Linu PR1

### PR DESCRIPTION
**Pull request by LinuToken**

### CODE REVIEW

**Comment by LinuToken** [comment]
Squid update 1

**Review by ecdsafu — APPROVED** [review]
lgtm

**Review by canhtrinh — APPROVED** [review]

**Comment by canhtrinh** [comment]
the json formatting is messy here for your token. can you resubmit the PR using the wizard?

**Comment by canhtrinh** [comment]
comment left last week was unaddressed. feel free to raise another PR with the suggestions above

**Pull request closed without merging**
