### PR TITLE
Feat/add KIP token

### PR DESCRIPTION
**Pull request by bizliaoyuan**
Adding KIP token to Squid token list.

https://kip.pro/

### CODE REVIEW

**Review by kipley-ai — APPROVED** [review]

**Comment by bizliaoyuan** [comment]
@benjamin852 Please help review this change. Thank you!

**Review by ecdsafu — COMMENTED** [review]
Hey guys, thanks for submitting. If you have a coingecko ID for this token could you please add it to the PR?

**Comment by bizliaoyuan** [comment]
Thank you for your review. We currently do not have a CoinGecko ID. If we obtain one, we will promptly submit a new PR to update it. Thank you! @ecdsafu

**Review by ecdsafu — APPROVED** [review]
lgtm

**Comment by bizliaoyuan** [comment]
I've resolved the code conflicts. Could you help me merge it?  @ecdsafu

**Review by Olanetsoft — APPROVED** [review]

**Pull request merged**
