### PR TITLE
feat: add coingecko id for its asset

### PR DESCRIPTION
**Pull request by Olanetsoft**

### CODE REVIEW

**Comment by pjenviri** [comment]
Hey @Olanetsoft, coingecko id should be obtained from this endpoint: https://api.coingecko.com/api/v3/coins/list rather than from the URL. In some cases, they are different, which can result in retrieving data for the wrong asset.

**Comment by Olanetsoft** [comment]
> Hey @Olanetsoft, coingecko id should be obtained from this endpoint: https://api.coingecko.com/api/v3/coins/list rather than from the URL. In some cases, they are different, which can result in retrieving data for the wrong asset.

Oh i see. I will double check.

**Comment by Olanetsoft** [comment]
Updated

**Review by canhtrinh — APPROVED** [review]

**Comment by StephenFluin** [comment]
@Olanetsoft What's the next step on this one?

**Comment by Olanetsoft** [comment]
> @Olanetsoft What's the next step on this one?

I am waiting on @canhtrinh to merge this and the most recent approved PRs to be scheduled for the next S3 release.

**Pull request merged**
