### PR TITLE
feat: add DeAl token

### PR DESCRIPTION
**Pull request by oshergluck**
Hi can you add DeAl token
Logo is
https://www.UltimateDeal.net/images/logoOfWebsite.svg

### CODE REVIEW

**Review by ecdsafu — CHANGES_REQUESTED** [review]
Hey guys, thanks for submitting. Could you please add coinGeckoId if the token is listed on coingecko, and upload the svg image to `images/tokens/deal.svg` in this repo for the pr?

**Comment by oshergluck** [comment]
I dont know how to add know the svg after creating the pull request...
take the svg from the link I gave you if you can I will appriciate it
and this is coingecko, after the presale we will take what left from it and put the raised amount and make liquidity in uniswap
https://www.geckoterminal.com/base/pools/0x943b73f79429ce02c0b8bfbd549057036b20ae5d
https://ultimatedeal.net/campaign-details/0

**Review by ecdsafu — APPROVED** [review]
lgtm

**Comment by ecdsafu** [comment]
> I dont know how to add now the svg after creating the pull request... take the svg from the link I gave you if you can I will appriciate it and this is coingecko, after the presale we will take what left from it and put the raised amount and make liquidity in uniswap https://www.geckoterminal.com/base/pools/0x943b73f79429ce02c0b8bfbd549057036b20ae5d https://ultimatedeal.net/campaign-details/0

Sounds good, I'll add after merge, then!

**Review by canhtrinh — APPROVED** [review]

**Pull request merged**
