### PR TITLE
Feat/add dackie & quack token

### PR DESCRIPTION
**Pull request by andreapn**
Feat/add dackie & quack token

### CODE REVIEW

**Comment by ecdsafu** [comment]
@andreapn it looks like both icons you've added are the AXL icon. Could you try changing them to dackie and quack?

**Comment by andreapn** [comment]
Sorry my fail copy T_T, already fixed

**Comment by andreapn** [comment]
@ecdsafu

**Review by ecdsafu — APPROVED** [review]
lgtm

**Comment by andreapn** [comment]
Hi @ecdsafu , already added coingeckoID

**Review by Olanetsoft — APPROVED** [review]

**Pull request closed without merging**
